spring.application.name=asistencia
# URL de conexión, usuario y contraseña
spring.datasource.url=jdbc:mysql://localhost:3306/asistencia
spring.datasource.username=root
spring.datasource.password=

# Estrategia de creación de tablas (update, create, none)
spring.jpa.hibernate.ddl-auto=validate
# Para ver las queries SQL en la consola (útil para debug)
spring.jpa.show-sql=true

# Nivel general: solo muestra advertencias y errores
logging.level.root=WARN

# Muestra info básica de tu aplicación (inicio y parada)
logging.level.com.supertesis.asistencia=INFO

# Silenciar por completo el banner de Spring (el dibujo al inicio)
spring.main.banner-mode=off

# Silenciar avisos específicos de Hibernate y Tomcat
logging.level.org.hibernate=ERROR
logging.level.org.apache.tomcat=ERROR
