- name: Set up JDK 25
      uses: actions/setup-java@v3
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      # Asegúrate de que 'run' esté alineado exactamente debajo de 'name'
      run: mvn -B package --file pom.xml -DskipTests